# Test embedalign with SentEval 

This notebook will allow you to test EmbedAlign using SentEval. In particular, this also works on **CPUs** :D

* Dependencies:
    * Python 3.5 with NumPy/SciPy
    * Pytorch 
    * Tensorflow 1.5.0  (for CPUs or GPUs depending on how you plan to run it)
        * For example in MacOS: 
        ```
        pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.5.0-py3-none-any.whl
        ```
    * scikit-learn>=0.18.0
    * dill>=0.2.7.1


* Install `dgm4nlp` by following the instructions [here](https://github.com/uva-slpl/dgm4nlp), we highly recommend the use of `virtualenv`.

In the same `virtualenv`, do the following:

* Clone repo from FAIR github
```
    git clone https://github.com/facebookresearch/SentEval.git
    cd SentEval/
```

* Install senteval
```
    python setup.py install
```

* Download datasets (it takes some time...)
    * these are downstream tasks
    * new Senteval also has probing tasks (https://github.com/facebookresearch/SentEval/tree/master/data/probing) for evaluating linguistic properties of your embeddings. 

```
    cd data/downstream/
    ./get_transfer_data.bash
```

* Download [pretained embedlaign model](https://surfdrive.surf.nl/files/index.php/s/9M4h5zqmYETSmf3)


* The following code evaluates embedalign pretrained embeddings on en-fr Europarl on different NLP downstream tasks.



In [1]:
from __future__ import absolute_import, division, unicode_literals

import sys
import numpy as np
import logging
import sklearn
#import data 
# data.py is part of Senteval and it is used for loading word2vec style files
import senteval
import tensorflow as tf
import logging
from collections import defaultdict
import dill
import dgm4nlp
import os

/home/tom/anaconda3/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# SkipGram imports
sys.path.append('../Practical 2/code/')
from models.skipgram import SkipGram
from helpers import load_model
import msgpack
import torch

In [3]:
import platform
platform.python_version()

'3.5.4'

In [4]:
class dotdict(dict):
    """ dot.notation access to dictionary attributes """
    __getattr__ = dict.get
    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__

class EmbeddingExtractor:
    """
    This will compute a forward pass with the inference model of EmbedAlign and 
        give you the variational mean for each L1 word in the batch.
        
    Note that this takes monolingual L1 sentences only (at this point we have a traiend EmbedAlign model
        which dispenses with L2 sentences).    
        
    You don't really want to touch anything in this class.
    """

    def __init__(self, graph_file, ckpt_path, config=None):        
        g1 = tf.Graph()
        self.meta_graph = graph_file
        self.ckpt_path = ckpt_path
        
        self.softmax_approximation = 'botev-batch' #default
        with g1.as_default():
            self.sess = tf.Session(config=config, graph=g1)
            # load architecture computational graph
            self.new_saver = tf.train.import_meta_graph(self.meta_graph)
            # restore checkpoint
            self.new_saver.restore(self.sess, self.ckpt_path) #tf.train.latest_checkpoint(
            self.graph = g1  #tf.get_default_graph()
            # retrieve input variable
            self.x = self.graph.get_tensor_by_name("X:0")
            # retrieve training switch variable (True:trianing, False:Test)
            self.training_phase = self.graph.get_tensor_by_name("training_phase:0")
            #self.keep_prob = self.graph.get_tensor_by_name("keep_prob:0")

    def get_z_embedding_batch(self, x_batch):
        """
        :param x_batch: is np array of shape [batch_size, longest_sentence] containing the unique ids of words
        
        :returns: [batch_size, longest_sentence, z_dim]        
        """
        # Retrieve embeddings from latent variable Z
        # we can sempale several n_samples, default 1
        try:
            z_mean = self.graph.get_tensor_by_name("z:0")
            
            feed_dict = {
                self.x: x_batch,
                self.training_phase: False,
                #self.keep_prob: 1.

            }
            z_rep_values = self.sess.run(z_mean, feed_dict=feed_dict) 
        except:
            raise ValueError('tensor Z not in graph!')
        return z_rep_values
    
def get_idf(batch):
    """
    Compute the idf of a batch of sentences, where we consider each sentence a 'document'.
    """
    df = defaultdict(lambda: 0)
    
    for sent in batch:
        for token in set(sent):
            df[token] += 1
    
    # Here we compute the batch-wise idf, log(1 + |batch| / |{s \in batch: w \in s}|), to tf-idf weigh sentence embeddings
    idf = {word: np.log(1 + len(batch) / float(frequency)) for word, frequency in df.items()}
    
    return idf
    

This is how you interface with SentEval. The only think you need to change are the paths to trained models in the main block at the end.

In [ ]:

# Set params for SentEval
# we use logistic regression (usepytorch: Fasle) and kfold 10
# In this dictionary you can add extra information that you model needs for initialization
# for example the path to a dictionary of indices, of hyper parameters
# this dictionary is passed to the batched and the prepare fucntions
params_senteval = {'task_path': '',
                   'usepytorch': False,
                   'kfold': 10,
                   'ckpt_path': '',
                   'tok_path': '',
                   'extractor': None,
                   'tks1': None,
                   'idf': False}
params_senteval = dotdict(params_senteval)

# this is the config for the NN classifier but we are going to use scikit-learn logistic regression with 10 kfold
# usepytorch = False 
#params_senteval['classifier'] = {'nhid': 0, 'optim': 'rmsprop', 'batch_size': 128,
#                                 'tenacity': 3, 'epoch_size': 2}


def prepare(params, samples):
    """
    In this example we are going to load a tensorflow model, 
    we open a dictionary with the indices of tokens and the computation graph
    """
    params.extractor = EmbeddingExtractor(
        graph_file='%s.meta'%(params.ckpt_path),
        ckpt_path=params.ckpt_path,
        config=None #run in cpu
    )

    # load tokenizer from training
    params.tks1 = dill.load(open(params.tok_path, 'rb'))
    return


def batcher(params, batch):
    """
    At this point batch is a python list containing sentences. Each sentence is a list of tokens (each token a string).
    The code below will take care of converting this to unique ids that EmbedAlign can understand.
    
    This function should return a single vector representation per sentence in the batch.
    In this example we use the average of word embeddings (as predicted by EmbedAlign) as a sentence representation.
    
    In this method you can do mini-batching or you can process sentences 1 at a time (batches of size 1).
    We choose to do it 1 sentence at a time to avoid having to deal with masking. 
    
    This should not be too slow, and it also saves memory.
    """
    # if a sentence is empty dot is set to be the only token
    # you can change it into NULL dependening in your model
    batch = [sent if sent != [] else ['.'] for sent in batch]
    # Here is where dgm4nlp converts strings to unique ids respecting the vocabulary
    # of the pre-trained EmbedAlign model
    # from tokens ot ids position 0 is en
    batch = [params.tks1[0].to_sequences([(' '.join(s))]) for s in batch]
    
    # The idf will be used to weigh embeddings when averaging
    if params.idf:
        idf = get_idf([list(s[0]) for s in batch])
        
    embeddings = []
    for x1 in batch:
        # extract word embeddings in context for a sentence
        # [1, sentence_length, z_dim]
        z_batch1 = params.extractor.get_z_embedding_batch(x_batch=x1)

        # sentence vector is the mean of word embeddings in context
        # [1, z_dim]
        if params.idf:
            weights = np.array([[[idf[token]] for token in list(x1[0])]])
            sent_vec = np.sum(z_batch1 * weights, axis=1) / np.sum(weights, axis=1)
        else:
            sent_vec = np.mean(z_batch1, axis=1)
            
        # check if there is any NaN in vector (they appear sometimes when there's padding)
        if np.isnan(sent_vec.sum()):
            sent_vec = np.nan_to_num(sent_vec)        
        embeddings.append(sent_vec)
    embeddings = np.vstack(embeddings)
    return embeddings


# Set up logger
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging.DEBUG)

if __name__ == "__main__":
    # Disable GPU, memory overflow error otherwise
    os.environ['CUDA_VISIBLE_DEVICES'] = ''
    # define paths
    # path to senteval data
    # note senteval adds downstream into the path
    params_senteval.task_path = '/home/tom/SentEval/data/' 
    # path to computation graph
    # we use best model on validation AER
    # TODO: you have to point to valid paths! Use the pre-trained model linked from the top of this notebook.
    params_senteval.ckpt_path = '/home/tom/Documents/ULL/Practical 3/data/ull-practical3-embedalign/model.best.validation.aer.ckpt'
    # path to tokenizer with ids of trained Europarl data
    # out dictionary id depends on dill for pickle
    params_senteval.tok_path = '/home/tom/Documents/ULL/Practical 3/data/ull-practical3-embedalign/tokenizer.pickle'
    # Whether to use idf
    params_senteval.idf = True
    
    # we use 10 fold cross validation
    params_senteval.kfold = 10
    se = senteval.engine.SE(params_senteval, batcher, prepare)
    
    # here you define the NLP taks that your embedding model is going to be evaluated
    # in (https://arxiv.org/abs/1802.05883) we use the following :
    # SICKRelatedness (Sick-R) needs torch cuda to work (even when using logistic regression), 
    # but STS14 (semantic textual similarity) is a similar type of semantic task
    transfer_tasks = ['MR', 'CR', 'MPQA', 'SUBJ', 'SST2', 'TREC',
                      'MRPC', 'SICKEntailment', 'STS14']
    # senteval prints the results and returns a dictionary with the scores
    results = se.eval(transfer_tasks)
    print(results)

2018-05-25 15:27:42,840 : ***** Transfer task : MR *****




INFO:tensorflow:Restoring parameters from /home/tom/Documents/ULL/Practical 3/data/ull-practical3-embedalign/model.best.validation.aer.ckpt


2018-05-25 15:27:43,589 : Restoring parameters from /home/tom/Documents/ULL/Practical 3/data/ull-practical3-embedalign/model.best.validation.aer.ckpt
2018-05-25 15:27:44,013 : Generating sentence embeddings
2018-05-25 15:28:26,312 : Generated sentence embeddings
2018-05-25 15:28:26,313 : Training sklearn-LogReg with (inner) 10-fold cross-validation
2018-05-25 15:28:38,851 : Best param found at split 1: l2reg = 8                 with score 63.96
2018-05-25 15:28:51,929 : Best param found at split 2: l2reg = 8                 with score 64.07
2018-05-25 15:29:05,113 : Best param found at split 3: l2reg = 8                 with score 64.21
2018-05-25 15:29:17,908 : Best param found at split 4: l2reg = 8                 with score 64.5


In [5]:
def prepare(params, samples):
    """
    We load the PyTorch model and accompanying word_to_index tokenizer.
    """
    params.extractor = load_model(params.ckpt_path, params.extractor)
    params.tokenizer = msgpack.unpack(open(params.tok_path, 'rb'), encoding='utf-8')
    
def batcher(params, batch):
    """
    At this point batch is a python list containing sentences. Each sentence is a list of tokens (each token a string).
    The code below will take care of converting this to unique ids that EmbedAlign can understand.
    
    This function should return a single vector representation per sentence in the batch.
    In this example we use the average of word embeddings (as predicted by SkipGram) as a sentence representation.
    
    In this method you can do mini-batching or you can process sentences 1 at a time (batches of size 1).
    We choose to do it 1 sentence at a time to avoid having to deal with masking. 
    
    This should not be too slow, and it also saves memory.
    """
    # if a sentence is empty dot is set to be the only token. We also remove UNKS as they bear no info, and tokenize
#     batch = [sent if sent != [] else ['.'] for sent in batch]
    batch = [[params.tokenizer[w] for w in s if w in params.tokenizer] if s != [] else [params.tokenizer['.']] for s in batch]
    embeddings = []
    
    if params.idf:
        df = defaultdict(lambda: 0)
        # Here we compute the batch-wise idf, log(1 + |batch| / |{s \in batch: w \in s}|), to tf-idf weigh sentence embeddings
        for sent in batch:
            for token in set(sent):
                df[token] += 1
    
        idf = {word: np.log(len(batch) / float(frequency)) for word, frequency in df.items()}
    
    for sent in batch:
        # Convert sentence to torch.tensor if not empty, else we set it to a dot again. 
        x = torch.tensor(sent, dtype=torch.long, device=params.device).unsqueeze(0) if sent else torch.tensor([params.tokenizer['.']], dtype=torch.long, device=params.device).unsqueeze(0)
        print(x, sent)
        
        # extract word embeddings in context for a sentence
        # [1, sentence_length, d_dim]
        word_embeddings = params.extractor.lst_pass(x)[0].unsqueeze(0)
        
        # sentence vector is the mean of word embeddings in context
        # [1, d_dim]
        if params.idf:
            # [1, sentence_length, 1] tensor of idfs per word
            weights = torch.tensor([idf[token] for token in sent] if sent else [1.], device=params.device).unsqueeze(0).unsqueeze(2)
#             print(weights, sent)
            # multiply embeddings by their weights and sum, dividing by total weight, yielding tf-idf weighed sent embedding 
            sent_embedding = (torch.sum(weights * word_embeddings, dim=1) / torch.sum(weights, dim=1)).cpu().detach().numpy()  
        else:
            sent_embedding = torch.mean(word_embeddings, dim=1).cpu().detach().numpy()
            
        embeddings.append(sent_embedding)
    embeddings = np.vstack(embeddings)
    return embeddings

# Set up logger
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging.DEBUG)

if __name__ == '__main__':
    # Enable GPU
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    
    # Base parameter list for skipgram
    params_skipgram = {'task_path': '',
                   'usepytorch': False,
                   'kfold': 10,
                   'ckpt_path': '',
                   'tok_path': '',
                   'extractor': None,
                   'tokenizer': None,
                   'idf': False,
                   'device': torch.device('cuda:0' if torch.cuda.is_available() else 'cpu') }
    params_skipgram = dotdict(params_skipgram)
    
    # Set paths
    params_skipgram.task_path = '/home/tom/SentEval/data/' 
    params_skipgram.ckpt_path = '/home/tom/Documents/ULL/Practical 2/out/europarl/skipgram_0_True_5_1.pt'
    params_skipgram.tok_path = '/home/tom/Documents/ULL/Practical 2/data/original/europarl/training_0_True_5_1_wordIndexMap.en'
    
    # Load v_dim
    v_dim = msgpack.load(open('/home/tom/Documents/ULL/Practical 2/data/original/europarl/pad_index_skipgram.en', 'rb')) + 1
    
    # Preload model
    params_skipgram.extractor = SkipGram(v_dim, 100, v_dim-1).to(params_skipgram.device)
    
    # Whether to use tf-idf weighed embeddings
    params_skipgram.idf = True
    
    # Execute SentEval tasks
    se = senteval.engine.SE(params_skipgram, batcher, prepare)
    
    # here you define the NLP taks that your embedding model is going to be evaluated
    # in (https://arxiv.org/abs/1802.05883) we use the following :
    # SICKRelatedness (Sick-R) needs torch cuda to work (even when using logistic regression), 
    # but STS14 (semantic textual similarity) is a similar type of semantic task
    transfer_tasks = ['MR', 'CR', 'MPQA', 'SUBJ', 'SST2', 'TREC',
                      'MRPC', 'SICKEntailment', 'STS14']
    # senteval prints the results and returns a dictionary with the scores
    results = se.eval(transfer_tasks)
    print(results)
    

2018-05-25 15:07:06,466 : ***** Transfer task : MR *****


2018-05-25 15:07:12,800 : Generating sentence embeddings


tensor([[ 1096]], device='cuda:0') [1096]
tensor([[ 25147]], device='cuda:0') [25147]
tensor([[ 63754]], device='cuda:0') [63754]
tensor([[ 52423,     29]], device='cuda:0') [52423, 29]
tensor([[ 22262,     29]], device='cuda:0') [22262, 29]
tensor([[ 29]], device='cuda:0') [29]
tensor([[ 78359,  20466]], device='cuda:0') [78359, 20466]
tensor([[ 4750,    29]], device='cuda:0') [4750, 29]
tensor([[ 23468,     29]], device='cuda:0') [23468, 29]
tensor([[ 62956,  13351]], device='cuda:0') [62956, 13351]
tensor([[ 35393,   2630]], device='cuda:0') [35393, 2630]
tensor([[ 11919,  29006]], device='cuda:0') [11919, 29006]
tensor([[ 2789]], device='cuda:0') [2789]
tensor([[ 36024,     29]], device='cuda:0') [36024, 29]
tensor([[ 10362,   2789]], device='cuda:0') [10362, 2789]
tensor([[ 13317,  40081,     29]], device='cuda:0') [13317, 40081, 29]
tensor([[ 13849,   6972,     29]], device='cuda:0') [13849, 6972, 29]
tensor([[ 2800,  4750,    29]], device='cuda:0') [2800, 4750, 29]
tensor([[ 241

tensor([[  9306,      2,  39853,   6972,     29]], device='cuda:0') [9306, 2, 39853, 6972, 29]
tensor([[ 133,   52,   73,   29]], device='cuda:0') [133, 52, 73, 29]
tensor([[  1786,   6972,     17,  12364,     29]], device='cuda:0') [1786, 6972, 17, 12364, 29]
tensor([[  4087,     55,  53745,     29]], device='cuda:0') [4087, 55, 53745, 29]
tensor([[ 1.0682e+05,  2.0000e+00,  1.1690e+05,  1.4024e+05,  2.9000e+01]], device='cuda:0') [106825, 2, 116903, 140242, 29]
tensor([[    55,   6600,  16255,     29]], device='cuda:0') [55, 6600, 16255, 29]
tensor([[  1782,    229,     76,  12002,     29]], device='cuda:0') [1782, 229, 76, 12002, 29]
tensor([[   984,     55,   5989,  13662,     29]], device='cuda:0') [984, 55, 5989, 13662, 29]
tensor([[    55,  53631,   1799,     29]], device='cuda:0') [55, 53631, 1799, 29]
tensor([[ 61061,     52,  18541,   5950,     29]], device='cuda:0') [61061, 52, 18541, 5950, 29]
tensor([[   998,   1047,  11550,  12411,     29]], device='cuda:0') [998, 1047, 1

tensor([[ 5.5000e+01,  5.5570e+03,  1.6300e+02,  1.3642e+05,  1.7990e+03,
          2.9000e+01]], device='cuda:0') [55, 5557, 163, 136419, 1799, 29]
tensor([[   55,  5866,    19,  8169,  1661,    29]], device='cuda:0') [55, 5866, 19, 8169, 1661, 29]
tensor([[ 5808,     2,    17,  8901,    29]], device='cuda:0') [5808, 2, 17, 8901, 29]
tensor([[    55,  34440,     19,     55,  16255,     29]], device='cuda:0') [55, 34440, 19, 55, 16255, 29]
tensor([[    55,  27186,      2,  66296,  16255,     29]], device='cuda:0') [55, 27186, 2, 66296, 16255, 29]
tensor([[    23,     55,   2111,  10405,     87,     29]], device='cuda:0') [23, 55, 2111, 10405, 87, 29]
tensor([[ 76946,  30106,     17,  53395,  30069,     29]], device='cuda:0') [76946, 30106, 17, 53395, 30069, 29]
tensor([[ 13849,  70540,     17,   1805,   2226,     29]], device='cuda:0') [13849, 70540, 17, 1805, 2226, 29]
tensor([[ 9.2004e+04,  1.2350e+03,  7.0000e+00,  1.1000e+01,  1.5488e+05,
          2.9000e+01]], device='cuda:0') [9

tensor([[ 26568,      2,  31278,      2,     17,  42596,  11055,     29]], device='cuda:0') [26568, 2, 31278, 2, 17, 42596, 11055, 29]
tensor([[ 3.6630e+03,  1.6400e+02,  1.1800e+03,  7.3300e+02,  1.1000e+01,
          1.0448e+05,  2.9000e+01]], device='cuda:0') [3663, 164, 1180, 733, 11, 104477, 29]
tensor([[   460,      0,     55,   4244,   6264,  11653,    147,     29]], device='cuda:0') [460, 0, 55, 4244, 6264, 11653, 147, 29]
tensor([[     3,  20041,    984,   1820,  41066,     14,   4765,     29]], device='cuda:0') [3, 20041, 984, 1820, 41066, 14, 4765, 29]
tensor([[    55,  24751,    528,   5397,     19,  53581,     29]], device='cuda:0') [55, 24751, 528, 5397, 19, 53581, 29]
tensor([[ 7.8300e+02,  2.3300e+02,  7.4450e+03,  2.6211e+04,  1.1000e+01,
          1.4532e+05,  1.3320e+03,  2.9000e+01]], device='cuda:0') [783, 233, 7445, 26211, 11, 145315, 1332, 29]
tensor([[  108,     2,    76,   445,   633,     9,  4112,    29]], device='cuda:0') [108, 2, 76, 445, 633, 9, 4112, 29]
t

tensor([[    55,  53711,      2,  43583,    163,    474,   4608,   5397,
             29]], device='cuda:0') [55, 53711, 2, 43583, 163, 474, 4608, 5397, 29]
tensor([[   181,    181,    444,    954,    129,  12946,  99360,     29]], device='cuda:0') [181, 181, 444, 954, 129, 12946, 99360, 29]
tensor([[  1077,    998,   3951,    101,  31335,    405,     52,  68940,
             29]], device='cuda:0') [1077, 998, 3951, 101, 31335, 405, 52, 68940, 29]
tensor([[ 4296,     2,    76,   129,    73,    29]], device='cuda:0') [4296, 2, 76, 129, 73, 29]
tensor([[    55,  14306,  21356,    229,   6489,     17,     49,  46542,
             29]], device='cuda:0') [55, 14306, 21356, 229, 6489, 17, 49, 46542, 29]
tensor([[    55,   4094,  32549,     19,     55,  10005,  43986,     29]], device='cuda:0') [55, 4094, 32549, 19, 55, 10005, 43986, 29]
tensor([[    11,    336,   7704,    181,     55,  11919,   7672,   4916,
             29]], device='cuda:0') [11, 336, 7704, 181, 55, 11919, 7672, 4916, 29]


tensor([[  5808,      2,  42865,      2,  13849,   2492,    110,     29]], device='cuda:0') [5808, 2, 42865, 2, 13849, 2492, 110, 29]
tensor([[  4420,     55,   4424,   6348,   9787,  32517,     29,     29,
             29]], device='cuda:0') [4420, 55, 4424, 6348, 9787, 32517, 29, 29, 29]
tensor([[    76,    129,  36094,    184,  36930,    646,     17,  10193,
           2012,     29]], device='cuda:0') [76, 129, 36094, 184, 36930, 646, 17, 10193, 2012, 29]
tensor([[    55,  89978,  16255,  73386,    110,    538,  30374,     19,
             29]], device='cuda:0') [55, 89978, 16255, 73386, 110, 538, 30374, 19, 29]
tensor([[  4485,      7,     55,   9787,  28173,     17,     55,   2502,
            993,     29]], device='cuda:0') [4485, 7, 55, 9787, 28173, 17, 55, 2502, 993, 29]
tensor([[    11,    336,    445,   1175,     76,    129,     55,  32517,
             29]], device='cuda:0') [11, 336, 445, 1175, 76, 129, 55, 32517, 29]
tensor([[ 1.4870e+05,  5.2000e+01,  5.5000e+01,  1.2960e

tensor([[   110,     11,    759,  12185,      2,     70,     11,  16226,
           3776,  11611,     29]], device='cuda:0') [110, 11, 759, 12185, 2, 70, 11, 16226, 3776, 11611, 29]
tensor([[   11,  1223,    52,   206,  5866,    93,  5988,   110,  9096,
            29]], device='cuda:0') [11, 1223, 52, 206, 5866, 93, 5988, 110, 9096, 29]
tensor([[    55,   1424,   2061,   7115,     17,     76,     52,     44,
          23718,     29]], device='cuda:0') [55, 1424, 2061, 7115, 17, 76, 52, 44, 23718, 29]
tensor([[   885,     11,  78552,      2,     52,   9369,    184,     11,
           1597,     29]], device='cuda:0') [885, 11, 78552, 2, 52, 9369, 184, 11, 1597, 29]
tensor([[ 28453,      2,  25178,   3709,     55,  19266,  37689,   2003,
             29]], device='cuda:0') [28453, 2, 25178, 3709, 55, 19266, 37689, 2003, 29]
tensor([[ 2.5400e+02,  1.2524e+05,  5.2000e+01,  1.8200e+03,  1.0960e+03,
          4.4800e+02,  1.4641e+04,  0.0000e+00,  1.3300e+02,  1.6255e+04,
          2.9000e+

tensor([[    11,    974,    804,    229,   4924,    104,  25644,     29]], device='cuda:0') [11, 974, 804, 229, 4924, 104, 25644, 29]
tensor([[  1473,    194,  16000,     11,  15902,     19,   9859,   7737,
           9802,     29]], device='cuda:0') [1473, 194, 16000, 11, 15902, 19, 9859, 7737, 9802, 29]
tensor([[   11,  5866,    52,  1828,   110,  5067,     2,  2365,  1232,
          2996,    29]], device='cuda:0') [11, 5866, 52, 1828, 110, 5067, 2, 2365, 1232, 2996, 29]
tensor([[ 53611,     23,   1293,     55,  19364,  49751,     17,   2011,
           4079,  19500,     29]], device='cuda:0') [53611, 23, 1293, 55, 19364, 49751, 17, 2011, 4079, 19500, 29]
tensor([[ 1.9500e+02,  1.2900e+02,  1.1000e+01,  1.1688e+05,  1.2185e+04,
          7.8300e+02,  3.4075e+04,  3.3700e+02,  1.6000e+02,  5.8960e+03,
          2.9000e+01]], device='cuda:0') [195, 129, 11, 116876, 12185, 783, 34075, 337, 160, 5896, 29]
tensor([[    55,  29056,  86741,      2,    984,     39,     11,    685,
          

tensor([[    55,  13671,     17,   4580,  56413,     19,     11,  68513,
            365,     19,   2734,     29]], device='cuda:0') [55, 13671, 17, 4580, 56413, 19, 11, 68513, 365, 19, 2734, 29]
tensor([[  9319,   7115,  73318,  17170,      2,  12290,      2,   6391,
             17,   1126,     29]], device='cuda:0') [9319, 7115, 73318, 17170, 2, 12290, 2, 6391, 17, 1126, 29]
tensor([[    55,   6343,    163,    285,  88147,      9,   9078,      2,
           4079,     17,  11640,     29]], device='cuda:0') [55, 6343, 163, 285, 88147, 9, 9078, 2, 4079, 17, 11640, 29]
tensor([[ 7.0000e+01,  1.1000e+02,  1.7000e+02,  8.4000e+02,  1.4306e+04,
          2.5358e+04,  2.0000e+00,  5.2770e+03,  2.0768e+04,  5.2000e+01,
          1.1197e+05,  2.9000e+01]], device='cuda:0') [70, 110, 170, 840, 14306, 25358, 2, 5277, 20768, 52, 111967, 29]
tensor([[ 1.1592e+05,  1.2900e+02,  3.6260e+03,  2.2399e+04,  2.8829e+04,
          5.2000e+01,  6.8020e+03,  1.8100e+02,  1.0800e+02,  1.8100e+02,
         

tensor([[    55,   5957,      2,  11833,   4625,   5866,     44,  12714,
           5852,   9769,      0,   6391,     29]], device='cuda:0') [55, 5957, 2, 11833, 4625, 5866, 44, 12714, 5852, 9769, 0, 6391, 29]
tensor([[    39,     17,      2,     11,    840,  49751,  16993,    405,
            159,  18471,     29]], device='cuda:0') [39, 17, 2, 11, 840, 49751, 16993, 405, 159, 18471, 29]
tensor([[  2484,      2,     93,     23,  17026,    181,  23826,    181,
             29,     93]], device='cuda:0') [2484, 2, 93, 23, 17026, 181, 23826, 181, 29, 93]
tensor([[    11,    974,   1894,    229,     11,  16255,     52,    170,
              2,  14685,   3965,     29]], device='cuda:0') [11, 974, 1894, 229, 11, 16255, 52, 170, 2, 14685, 3965, 29]
tensor([[    11,  28173,     52,     55,   3798,      2,     65,  44652,
           1686,     17,  22141,  17280,     29]], device='cuda:0') [11, 28173, 52, 55, 3798, 2, 65, 44652, 1686, 17, 22141, 17280, 29]
tensor([[ 1.5064e+05,  1.9917e+04,  2.1

tensor([[    17,    753,    515,     46,     47,     11,  26015,     19,
             86,  12706,     29]], device='cuda:0') [17, 753, 515, 46, 47, 11, 26015, 19, 86, 12706, 29]
tensor([[     3,  70883,   2080,    339,    389,    618,    959,    110,
             55,    759,   6086,   6235,     29]], device='cuda:0') [3, 70883, 2080, 339, 389, 618, 959, 110, 55, 759, 6086, 6235, 29]
tensor([[   11,   335,  1223,    52,   206,  4671,     2,   285,  9644,
            19,  5633,  1683,    29]], device='cuda:0') [11, 335, 1223, 52, 206, 4671, 2, 285, 9644, 19, 5633, 1683, 29]
tensor([[  612,  1786,   181,    55,  1878,  2492,    17,   181,    55,
          2226,  7737,  1798,    29]], device='cuda:0') [612, 1786, 181, 55, 1878, 2492, 17, 181, 55, 2226, 7737, 1798, 29]
tensor([[  4143,    236,    796,  16993,     19,  22332,      0,   9527,
             17,  26883,   5490,     29]], device='cuda:0') [4143, 236, 796, 16993, 19, 22332, 0, 9527, 17, 26883, 5490, 29]
tensor([[ 2.8850e+03,  2.81

tensor([[    76,     23,   3186,   5948,     44,     11,  45282,    129,
            974,    819,    159,    407,   2485,     29]], device='cuda:0') [76, 23, 3186, 5948, 44, 11, 45282, 129, 974, 819, 159, 407, 2485, 29]
tensor([[   445,    515,    281,   5390,   3582,    843,     76,    460,
          28782,  34310,  22652,  15307,     29]], device='cuda:0') [445, 515, 281, 5390, 3582, 843, 76, 460, 28782, 34310, 22652, 15307, 29]
tensor([[    73,    984,     29,  15221,     29,  13860,     29,    261,
            794,  43979,    368,   6692,     29]], device='cuda:0') [73, 984, 29, 15221, 29, 13860, 29, 261, 794, 43979, 368, 6692, 29]
tensor([[    52,   7132,   1590,      2,    163,     11,   2008,   8340,
          30398,     11,   2564,     29]], device='cuda:0') [52, 7132, 1590, 2, 163, 11, 2008, 8340, 30398, 11, 2564, 29]
tensor([[    11,  54733,    194,     52,  84215,   1273,     11,   2008,
             17,  19500,    967,  23718,     29]], device='cuda:0') [11, 54733, 194, 52,

tensor([[    11,  25948,  20811,      2,     39,    170,   5984,   9527,
              2,     52,    210,     19,   2250,     29]], device='cuda:0') [11, 25948, 20811, 2, 39, 170, 5984, 9527, 2, 52, 210, 19, 2250, 29]
tensor([[    30,    783,  35827,     55,   8640,    684,      2,   1826,
           7496,    281,   1194,      2,    254,    957]], device='cuda:0') [30, 783, 35827, 55, 8640, 684, 2, 1826, 7496, 281, 1194, 2, 254, 957]
tensor([[   322,   2102,    759,   8555,   4299,  16255,     52,     55,
          58626,      2,  10720,     29,     29,     29]], device='cuda:0') [322, 2102, 759, 8555, 4299, 16255, 52, 55, 58626, 2, 10720, 29, 29, 29]
tensor([[ 9.9800e+02,  2.5838e+04,  7.8300e+02,  1.8834e+04,  6.0000e+00,
          4.7000e+01,  3.8900e+02,  5.8670e+03,  2.3510e+03,  2.9000e+01,
          1.3860e+03,  1.3300e+02,  3.1520e+03,  1.5136e+05,  2.9000e+01]], device='cuda:0') [998, 25838, 783, 18834, 6, 47, 389, 5867, 2351, 29, 1386, 133, 3152, 151359, 29]
tensor([[    11, 

tensor([[   206,   4956,  16691,     17,  37838,  20925,    606,     65,
          27701,    757,  27701,    757,  27701,     29]], device='cuda:0') [206, 4956, 16691, 17, 37838, 20925, 606, 65, 27701, 757, 27701, 757, 27701, 29]
tensor([[ 1.9490e+03,  2.0000e+00,  1.3239e+04,  1.2542e+05,  2.9000e+01,
          6.6190e+03,  1.3239e+04,  5.3570e+04,  2.9000e+01]], device='cuda:0') [1949, 2, 13239, 125419, 29, 6619, 13239, 53570, 29]
tensor([[ 63854,     23,    441,     55,  11188,    829,   1159,     44,
             52,   7064,      2,     17,   8100,     29]], device='cuda:0') [63854, 23, 441, 55, 11188, 829, 1159, 44, 52, 7064, 2, 17, 8100, 29]
tensor([[ 2.0600e+02,  4.2900e+03,  1.7000e+01,  4.2190e+04,  1.6255e+04,
          4.4000e+01,  1.1040e+05,  1.2350e+03,  2.9900e+02,  1.1000e+01,
          2.3940e+04,  1.4030e+03,  1.9000e+01,  2.2480e+03,  2.9000e+01]], device='cuda:0') [206, 4290, 17, 42190, 16255, 44, 110395, 1235, 299, 11, 23940, 1403, 19, 2248, 29]
tensor([[    44,  2

tensor([[    55,  30798,     19,  12236,    232,   7317,      2,     76,
              6,    557,    362,    110,  47196,    840,   8922,     29]], device='cuda:0') [55, 30798, 19, 12236, 232, 7317, 2, 76, 6, 557, 362, 110, 47196, 840, 8922, 29]
tensor([[ 24751,  19599,     17,    108,   6906,     29,     29,     29,
            163,  12445,   7686,    110,    170,  16550,   1192,     29]], device='cuda:0') [24751, 19599, 17, 108, 6906, 29, 29, 29, 163, 12445, 7686, 110, 170, 16550, 1192, 29]
tensor([[ 1.1064e+05,  2.9000e+01,  3.0000e+00,  1.6400e+02,  7.3000e+01,
          4.0600e+02,  1.3300e+02,  2.1640e+03,  1.8400e+02,  5.5000e+01,
          1.6255e+04,  1.1000e+02,  5.5000e+01,  4.0700e+02,  9.1700e+02,
          2.9000e+01]], device='cuda:0') [110644, 29, 3, 164, 73, 406, 133, 2164, 184, 55, 16255, 110, 55, 407, 917, 29]
tensor([[    76,   3776,  10343,   1656,    184,   3536,   7276,  30349,
            131,   4008,     14,     11,   2800,     49,  20810,     29]], device='cud

tensor([[    76,      6,  22991,  31508,     14,     11,   1798,     17,
           1201,      5,   1175,     76,      7,  44953,   4430,     29]], device='cuda:0') [76, 6, 22991, 31508, 14, 11, 1798, 17, 1201, 5, 1175, 76, 7, 44953, 4430, 29]
tensor([[ 14739,      2,   4220,    325,     76,     52,    978,     19,
            170,   1713,  10616,     19,     11,   4786,     29]], device='cuda:0') [14739, 2, 4220, 325, 76, 52, 978, 19, 170, 1713, 10616, 19, 11, 4786, 29]
tensor([[   392,     19,     11,    974,      2,    840,  46774,  26015,
             19,   4420,  12179,  11255,    129,   4424,   1359,     29]], device='cuda:0') [392, 19, 11, 974, 2, 840, 46774, 26015, 19, 4420, 12179, 11255, 129, 4424, 1359, 29]
tensor([[   261,  53706,      2,  57586,   1552,   1963,     65,   1473,
           4671,  10616,     19,    591,  72475,     17,   9298,     29]], device='cuda:0') [261, 53706, 2, 57586, 1552, 1963, 65, 1473, 4671, 10616, 19, 591, 72475, 17, 9298, 29]
tensor([[    76,    

tensor([[ 23838,      0,    129,  16312,     17,   1473,   5266,   8688,
              0,  51234,     31,    422,    195,   4554,     29]], device='cuda:0') [23838, 0, 129, 16312, 17, 1473, 5266, 8688, 0, 51234, 31, 422, 195, 4554, 29]
tensor([[ 11546,   7898,    517,      2,   2890,     11,  16255,    129,
            151,     17,  26567,    170,  15961,    129,  17279,   5212,
             29]], device='cuda:0') [11546, 7898, 517, 2, 2890, 11, 16255, 129, 151, 17, 26567, 170, 15961, 129, 17279, 5212, 29]
tensor([[   254,   4010,     19,   5424,     17,   8844,  32004,  75310,
            233,  10984,    133,  16255,    129,   2056,     19,    690,
             29]], device='cuda:0') [254, 4010, 19, 5424, 17, 8844, 32004, 75310, 233, 10984, 133, 16255, 129, 2056, 19, 690, 29]
tensor([[  6277,  86958,   1789,    399,    819,      2,   1789,   2634,
            819,     17,  70696,   1789,    101,    118,   4003,     29]], device='cuda:0') [6277, 86958, 1789, 399, 819, 2, 1789, 2634, 81

tensor([[   110,   1473,  11424,    181,     55,   5866,   4689,      2,
           5992,  21126,     55,  12899,     17,   2017,    194,     29]], device='cuda:0') [110, 1473, 11424, 181, 55, 5866, 4689, 2, 5992, 21126, 55, 12899, 17, 2017, 194, 29]
tensor([[   206,  10794,    163,  24685,  19500,     44,     52,    804,
          32563,     17,    804,  25253,     19,     11,   3844,  20115,
             29]], device='cuda:0') [206, 10794, 163, 24685, 19500, 44, 52, 804, 32563, 17, 804, 25253, 19, 11, 3844, 20115, 29]
tensor([[ 4.2200e+02,  1.1000e+01,  4.9420e+03,  7.5975e+04,  4.4500e+02,
          1.1950e+03,  4.5000e+02,  2.0000e+00,  1.2587e+05,  5.2000e+01,
          7.3010e+03,  5.5000e+01,  3.8480e+03,  4.4260e+03,  6.3638e+04,
          2.9000e+01]], device='cuda:0') [422, 11, 4942, 75975, 445, 1195, 450, 2, 125867, 52, 7301, 55, 3848, 4426, 63638, 29]
tensor([[  3141,      2,   1782,  15164,     39,   5916,  40444,     29,
             17,    110,    133,   1298,      2,   

tensor([[ 5.4000e+01,  1.2900e+02,  5.5000e+01,  3.5393e+04,  5.8186e+04,
          1.6255e+04,  1.4000e+01,  4.7000e+01,  5.2800e+02,  7.0000e+00,
          1.4332e+05,  2.0000e+00,  1.6300e+02,  1.1556e+05,  5.2000e+01,
          7.6000e+01,  2.9000e+01]], device='cuda:0') [54, 129, 55, 35393, 58186, 16255, 14, 47, 528, 7, 143321, 2, 163, 115563, 52, 76, 29]
tensor([[    55,   1224,   5867,   1580,    783,  12462,    874,     76,
              2,    783,   4052,    783,  12462,    406,     14,     11,
           3663,     29]], device='cuda:0') [55, 1224, 5867, 1580, 783, 12462, 874, 76, 2, 783, 4052, 783, 12462, 406, 14, 11, 3663, 29]
tensor([[    11,  39462,    129,  12437,     52,   6628,      2,    163,
             76,    233,    235,    605,     55,   7686,  19568,    622,
             29]], device='cuda:0') [11, 39462, 129, 12437, 52, 6628, 2, 163, 76, 233, 235, 605, 55, 7686, 19568, 622, 29]
tensor([[     3,  70883,     47,   1826,   5619,     14,    227,     19,
            

tensor([[  8251,  23718,     17,   4735,  11981,      2,     17,     76,
           5554,   8417,    108,    181,     55,   8555,   3315,      0,
          29988,     29]], device='cuda:0') [8251, 23718, 17, 4735, 11981, 2, 17, 76, 5554, 8417, 108, 181, 55, 8555, 3315, 0, 29988, 29]
tensor([[    76,    129,   7435,      2,    163,     76,  18865,   1199,
             11,   2354,  59253,     65,   4725,     17,     70,    236,
           3268,     29]], device='cuda:0') [76, 129, 7435, 2, 163, 76, 18865, 1199, 11, 2354, 59253, 65, 4725, 17, 70, 236, 3268, 29]
tensor([[    55,  10748,     17,   1138,   4330,     19,    532,     11,
          69447,     22,   2231,    206,   5542,  19979,    110,   2577,
            901,     29]], device='cuda:0') [55, 10748, 17, 1138, 4330, 19, 532, 11, 69447, 22, 2231, 206, 5542, 19979, 110, 2577, 901, 29]
tensor([[    55,  52395,   1424,      9,     11,   5866,   3206,      2,
            163,    392,     44,     25,     96,     31,    281,   5596,
   

tensor([[   11,  1798,    23,   170,  9373,     2,    17,    11,  3126,
           983,     2,    73,    99,  3104,     2,   159,  3141,    29]], device='cuda:0') [11, 1798, 23, 170, 9373, 2, 17, 11, 3126, 983, 2, 73, 99, 3104, 2, 159, 3141, 29]
tensor([[   110,    170,    974,  16993,      2,  11735,     55,   1590,
            477,   8172,    861,     19,  58031,      2,    261,   3235,
             19,   7888,     29]], device='cuda:0') [110, 170, 974, 16993, 2, 11735, 55, 1590, 477, 8172, 861, 19, 58031, 2, 261, 3235, 19, 7888, 29]
tensor([[ 3.7934e+04,  2.9240e+03,  1.4000e+01,  1.6400e+02,  1.4620e+04,
          1.4730e+03,  1.5610e+03,  9.9300e+02,  9.0000e+00,  1.5288e+05,
          5.9200e+02,  1.7000e+01,  4.3100e+02,  1.7820e+03,  1.0680e+03,
          1.1030e+03,  0.0000e+00,  1.2903e+04,  2.9000e+01]], device='cuda:0') [37934, 2924, 14, 164, 14620, 1473, 1561, 993, 9, 152880, 592, 17, 431, 1782, 1068, 1103, 0, 12903, 29]
tensor([[    54,     52,    254,   4040,    110,   6

tensor([[    76,   1517,    629,     55,   3792,     19,   1569,     44,
            129,     99,   1056,      7,     27,   1713,     17,   2365,
          17673,  23452,     29]], device='cuda:0') [76, 1517, 629, 55, 3792, 19, 1569, 44, 129, 99, 1056, 7, 27, 1713, 17, 2365, 17673, 23452, 29]
tensor([[ 5.5000e+01,  6.4791e+04,  2.0000e+00,  1.1833e+04,  2.0000e+00,
          2.2005e+04,  2.2695e+04,  3.0798e+04,  1.9000e+01,  5.5000e+01,
          5.2060e+03,  5.0000e+00,  1.2900e+02,  1.1000e+01,  1.1688e+05,
          1.9000e+01,  5.0753e+04,  2.9000e+01]], device='cuda:0') [55, 64791, 2, 11833, 2, 22005, 22695, 30798, 19, 55, 5206, 5, 129, 11, 116876, 19, 50753, 29]
tensor([[   335,      2,     76,    129,     55,     99,  49751,      2,
          56288,   5866,     65,     55,   6619,   2003,    843,   2029,
             52,   7737,     29]], device='cuda:0') [335, 2, 76, 129, 55, 99, 49751, 2, 56288, 5866, 65, 55, 6619, 2003, 843, 2029, 52, 7737, 29]
tensor([[   344,  19981,      

tensor([[  1169,     14,     47,   7892,     19,    463,      2,   1302,
          12134,      2,   1582,   2041,      2,     21,   4689,  12610,
          13901,  51098,  11619,     29]], device='cuda:0') [1169, 14, 47, 7892, 19, 463, 2, 1302, 12134, 2, 1582, 2041, 2, 21, 4689, 12610, 13901, 51098, 11619, 29]
tensor([[ 13358,  17668,  18996,  29757,   1661,      2,     70,    181,
             76,    169,   9078,   1482,    496,    181,  20466,      2,
          13099,     17,   3525,     29]], device='cuda:0') [13358, 17668, 18996, 29757, 1661, 2, 70, 181, 76, 169, 9078, 1482, 496, 181, 20466, 2, 13099, 17, 3525, 29]
tensor([[   885,    594,  13037,  60741,     17,  68524,  31038,      2,
             52,    984,   1820,     14,     47,     45,    129,  94428,
             29]], device='cuda:0') [885, 594, 13037, 60741, 17, 68524, 31038, 2, 52, 984, 1820, 14, 47, 45, 129, 94428, 29]
tensor([[    11,   5866,    260,      7,    707,    206,   6427,   9527,
           2492,     14,     

tensor([[    29,     29,     29,     54,    129,   1827,  20724,  22643,
            405,     14,   6343,     11,  11037,     19,  86958,  14538,
             19,    160,  15388,     29]], device='cuda:0') [29, 29, 29, 54, 129, 1827, 20724, 22643, 405, 14, 6343, 11, 11037, 19, 86958, 14538, 19, 160, 15388, 29]
tensor([[   618,      2,   5676,      2,     17,     11,  65636,    235,
           1651,  31928,    299,    206,  11427,      2,  10595,     17,
           4671,   2239,     29]], device='cuda:0') [618, 2, 5676, 2, 17, 11, 65636, 235, 1651, 31928, 299, 206, 11427, 2, 10595, 17, 4671, 2239, 29]
tensor([[  1427,    261,    783,     52,     55,  15072,   4330,     19,
             55,   6151,   9078,    541,     82,     55,   1224,   6539,
           3106,     29]], device='cuda:0') [1427, 261, 783, 52, 55, 15072, 4330, 19, 55, 6151, 9078, 541, 82, 55, 1224, 6539, 3106, 29]
tensor([[ 1.8770e+03,  1.1787e+05,  1.2900e+02,  9.2950e+03,  2.2310e+03,
          1.9821e+04,  2.0000e+00, 

tensor([[    11,   3314,    159,   1302,    144,     11,    476,    647,
           3005,      2,  23718,      2,   2226,    103,     39,   7737,
            110,    759,   6086,    649,     29]], device='cuda:0') [11, 3314, 159, 1302, 144, 11, 476, 647, 3005, 2, 23718, 2, 2226, 103, 39, 7737, 110, 759, 6086, 649, 29]
tensor([[   232,   9726,     14,     11,  16835,     19,     11,      2,
          50245,    181,     14,    164,   8922,  89556,      7,     11,
            151,   5596,     29]], device='cuda:0') [232, 9726, 14, 11, 16835, 19, 11, 2, 50245, 181, 14, 164, 8922, 89556, 7, 11, 151, 5596, 29]
tensor([[ 5.5000e+01,  1.1762e+05,  2.0000e+00,  8.3541e+04,  1.3662e+04,
          2.9000e+01,  2.9000e+01,  2.9000e+01,  9.8400e+02,  5.5000e+01,
          2.9704e+04,  7.6800e+02,  0.0000e+00,  5.5000e+01,  5.5923e+04,
          4.0190e+03,  1.9000e+01,  5.5000e+01,  1.6255e+04,  2.9000e+01]], device='cuda:0') [55, 117625, 2, 83541, 13662, 29, 29, 29, 984, 55, 29704, 768, 0, 55, 559

tensor([[ 5.5000e+01,  3.0460e+03,  1.3783e+05,  8.0847e+04,  4.0578e+04,
          1.9000e+01,  6.8000e+02,  1.9400e+04,  4.4000e+01,  2.5040e+04,
          5.5000e+01,  3.5450e+03,  1.8200e+03,  9.3100e+02,  9.1700e+02,
          9.0000e+00,  1.7000e+02,  2.1780e+03,  9.4040e+03,  1.8810e+03,
          2.9000e+01]], device='cuda:0') [55, 3046, 137826, 80847, 40578, 19, 680, 19400, 44, 25040, 55, 3545, 1820, 931, 917, 9, 170, 2178, 9404, 1881, 29]
tensor([[    76,    129,     73,     11,    118,     19,   8517,  22774,
             44,    133,  17072,  44643,    191,     47,  11109,     14,
             11,  10687,     19,   1732,     29]], device='cuda:0') [76, 129, 73, 11, 118, 19, 8517, 22774, 44, 133, 17072, 44643, 191, 47, 11109, 14, 11, 10687, 19, 1732, 29]
tensor([[ 2.9000e+01,  2.9000e+01,  2.9000e+01,  4.1630e+03,  1.8270e+03,
          1.9904e+04,  2.9900e+02,  1.1000e+01,  1.9319e+04,  1.9000e+01,
          1.1000e+01,  1.3107e+04,  1.7000e+01,  1.1036e+05,  2.6050e+03,
   

tensor([[    55,   5866,    528,     65,    181,   1424,  22302,      2,
            790,      2,     17,   4704,    181,  89528,    439,      0,
             55,  39352,  43986,     29]], device='cuda:0') [55, 5866, 528, 65, 181, 1424, 22302, 2, 790, 2, 17, 4704, 181, 89528, 439, 0, 55, 39352, 43986, 29]
tensor([[ 12716,    783,    184,  12890,    210,    232,     25,   4469,
          36980,      2,    232,     25,  12411,  14605,      2,     44,
             11,   6426,   4895,   9157,   4508,     29]], device='cuda:0') [12716, 783, 184, 12890, 210, 232, 25, 4469, 36980, 2, 232, 25, 12411, 14605, 2, 44, 11, 6426, 4895, 9157, 4508, 29]
tensor([[    11,   8099,     52,   1267,     17,  23718,      2,      0,
             11,    350,    357,    390,   2335,   1273,   1580,     44,
              2,     11,   8043,  51167,   5379,     29]], device='cuda:0') [11, 8099, 52, 1267, 17, 23718, 2, 0, 11, 350, 357, 390, 2335, 1273, 1580, 44, 2, 11, 8043, 51167, 5379, 29]
tensor([[ 22071,  67019

tensor([[  4744,     55,  77044,  56413,     19,     55,   6151,   9078,
             44,     52,     96,    198,     17,   3384,    144,   4606,
           3966,    110,     55,  39352,   5866,     29]], device='cuda:0') [4744, 55, 77044, 56413, 19, 55, 6151, 9078, 44, 52, 96, 198, 17, 3384, 144, 4606, 3966, 110, 55, 39352, 5866, 29]
tensor([[ 28409,   1552,    206,   4761,   2920,    181,    108,    181,
            236,   4671,   6389,      9,     11,   1397,     19,  43582,
            110,     11,   1733,     18,     29]], device='cuda:0') [28409, 1552, 206, 4761, 2920, 181, 108, 181, 236, 4671, 6389, 9, 11, 1397, 19, 43582, 110, 11, 1733, 18, 29]
tensor([[ 5.2000e+01,  5.5784e+04,  1.8400e+02,  8.5998e+04,  1.2900e+02,
          1.4613e+04,  1.3627e+04,  2.0000e+00,  5.9400e+02,  1.3120e+05,
          2.0000e+00,  1.7000e+01,  3.2500e+02,  1.9000e+01,  4.4000e+01,
          2.0000e+00,  1.4730e+03,  5.8660e+03,  2.9000e+01]], device='cuda:0') [52, 55784, 184, 85998, 129, 14613, 1

tensor([[ 4.8388e+04,  5.5000e+01,  5.1200e+02,  1.0858e+05,  9.5700e+02,
          4.4200e+03,  3.6334e+04,  4.4240e+03,  4.9870e+03,  7.6000e+01,
          9.0000e+00,  2.3200e+02,  7.3910e+03,  1.3300e+02,  9.1700e+02,
          4.4000e+01,  7.6000e+01,  8.4060e+03,  3.9000e+01,  5.5000e+01,
          3.1890e+03,  5.6520e+03,  2.9000e+01]], device='cuda:0') [48388, 55, 512, 108582, 957, 4420, 36334, 4424, 4987, 76, 9, 232, 7391, 133, 917, 44, 76, 8406, 39, 55, 3189, 5652, 29]
tensor([[    54,    129,     55,   2111,   1798,   6750,    110,    405,
              2,    163,    783,  70883,    164,     14,  20042,   4244,
           2223,     14,  27195,     76,     29]], device='cuda:0') [54, 129, 55, 2111, 1798, 6750, 110, 405, 2, 163, 783, 70883, 164, 14, 20042, 4244, 2223, 14, 27195, 76, 29]
tensor([[ 6.5000e+01,  1.7000e+02,  3.8826e+04,  3.9352e+04,  1.3594e+05,
          1.7000e+01,  1.1000e+01,  1.0430e+04,  1.6884e+04,  1.9000e+01,
          1.7000e+02,  1.7280e+04,  2.0020e+0

tensor([[   885,     11,    407,   3625,    917,      2,     11,   4447,
           1281,   8406,  10193,   7115,     54,    129,    254,   6216,
             44,  72121,  38568,   5030,   2789]], device='cuda:0') [885, 11, 407, 3625, 917, 2, 11, 4447, 1281, 8406, 10193, 7115, 54, 129, 254, 6216, 44, 72121, 38568, 5030, 2789]
tensor([[    11,    974,  16255,     19,    170,    575,    117,     29,
             93,  14751,      2,    266,   3740,     29,    133,     52,
            532,    783,    701,    817,    716,     29]], device='cuda:0') [11, 974, 16255, 19, 170, 575, 117, 29, 93, 14751, 2, 266, 3740, 29, 133, 52, 532, 783, 701, 817, 716, 29]
tensor([[    22,  42865,     17,    606,     65,  58286,      2,    163,
          49751,   1827,    101,    368,     93,     14,   4168,     14,
            681,    376,      0,    521,   1056,     29]], device='cuda:0') [22, 42865, 17, 606, 65, 58286, 2, 163, 49751, 1827, 101, 368, 93, 14, 4168, 14, 681, 376, 0, 521, 1056, 29]
tensor([[   

tensor([[   261,   4420,    829,   4424,      2,   4411,    184,     11,
           2052,    191,  18899,    562,     11,  16143,     29,    195,
          36527,     76,   1789,      2,  92748,     29]], device='cuda:0') [261, 4420, 829, 4424, 2, 4411, 184, 11, 2052, 191, 18899, 562, 11, 16143, 29, 195, 36527, 76, 1789, 2, 92748, 29]
tensor([[    55,   4926,  25330,   1799,     44,   1232,  28731,     11,
          10285,     17,  10179,     19,   7499,    110,     55,   1040,
             44,   1224,   3663,    164,    145,   4682,     29]], device='cuda:0') [55, 4926, 25330, 1799, 44, 1232, 28731, 11, 10285, 17, 10179, 19, 7499, 110, 55, 1040, 44, 1224, 3663, 164, 145, 4682, 29]
tensor([[ 11818,     17,   1763,     19,  22494,    377,  22494,      2,
           2488,     14,    594,     52,     55,    129,  14204,      2,
            206,   6748,     14,   5174,   9521,     29]], device='cuda:0') [11818, 17, 1763, 19, 22494, 377, 22494, 2, 2488, 14, 594, 52, 55, 129, 14204, 2, 206, 

tensor([[ 4420,  9612,  4424,   195,  5866,    52,  1281,  1663,    14,
           235,    55,   137,  1665,    70,   200,    76,  8745,    14,
          5476,     9,   206,  5542,  2312,    29]], device='cuda:0') [4420, 9612, 4424, 195, 5866, 52, 1281, 1663, 14, 235, 55, 137, 1665, 70, 200, 76, 8745, 14, 5476, 9, 206, 5542, 2312, 29]
tensor([[    11,  59649,  23257,    170,    917,      9,  19294,    870,
            144,  22751,     65,     11,   6269,  16376,     19,    129,
           1045,    517,     11,    347,  19669,     29]], device='cuda:0') [11, 59649, 23257, 170, 917, 9, 19294, 870, 144, 22751, 65, 11, 6269, 16376, 19, 129, 1045, 517, 11, 347, 19669, 29]
tensor([[ 1.1000e+01,  6.6430e+03,  2.3000e+01,  5.5000e+01,  7.8800e+02,
          1.7970e+03,  1.6300e+02,  3.9200e+02,  2.4360e+03,  1.5800e+03,
          1.8700e+02,  5.2000e+01,  7.3000e+01,  1.1000e+01,  9.7900e+02,
          1.8100e+02,  3.9200e+02,  2.4360e+03,  3.8300e+02,  1.8400e+02,
          3.4310e+04,  1.550

tensor([[  7501,    129,   2012,      2,   1582,    594,  69088,  10748,
            701,     19,     17,    594,  13138,     65,     55,   2011,
          34976,      2,   4143,  53107,   4718,     29]], device='cuda:0') [7501, 129, 2012, 2, 1582, 594, 69088, 10748, 701, 19, 17, 594, 13138, 65, 55, 2011, 34976, 2, 4143, 53107, 4718, 29]
tensor([[   11,  8169,  1966,    52,    55,  1590,  5866,     2,    76,
           129,   984,   392,    44,   603,  1437,  2450,     0,   257,
           932,  1848,  1769,  5123,    29]], device='cuda:0') [11, 8169, 1966, 52, 55, 1590, 5866, 2, 76, 129, 984, 392, 44, 603, 1437, 2450, 0, 257, 932, 1848, 1769, 5123, 29]
tensor([[    11,   3790,  26015,    184,   7115,     17,   1582,  42099,
              2,    206,   1966,  37938,      5,    686,   2940,   6721,
           7115,    619,    210,     11,   6352,  27011,     29]], device='cuda:0') [11, 3790, 26015, 184, 7115, 17, 1582, 42099, 2, 206, 1966, 37938, 5, 686, 2940, 6721, 7115, 619, 210, 11, 6

tensor([[    76,   3207,     14,     47,    381,     19,    181,     55,
          29520,   1424,   5866,      2,    163,     76,     23,    160,
             11,  12763,     19,     55,   4426,    223,  32517,     29]], device='cuda:0') [76, 3207, 14, 47, 381, 19, 181, 55, 29520, 1424, 5866, 2, 163, 76, 23, 160, 11, 12763, 19, 55, 4426, 223, 32517, 29]
tensor([[ 5.4000e+01,  1.5900e+02,  5.5000e+01,  1.2240e+03,  5.9630e+04,
          1.7000e+01,  1.6691e+04,  3.4690e+03,  6.6255e+04,  9.7480e+03,
          2.2900e+02,  2.0000e+00,  1.6300e+02,  7.3000e+01,  1.8270e+03,
          1.4000e+01,  2.3500e+02,  1.3300e+02,  4.6060e+03,  9.6000e+01,
          1.4400e+02,  1.8700e+02,  1.1576e+05,  7.4480e+03,  2.9000e+01]], device='cuda:0') [54, 159, 55, 1224, 59630, 17, 16691, 3469, 66255, 9748, 229, 2, 163, 73, 1827, 14, 235, 133, 4606, 96, 144, 187, 115756, 7448, 29]
tensor([[    70,   1201,     19,     55,    301,  94923,   2670,      6,
             47,    621,     14,   4541,     44,  

tensor([[   477,   2828,  46786,    232,   7602,      7,    463,   3663,
             17,   6213,   1827,   4996,   6603,     19,  12134,     44,
             76,  76206,    732,    163,   5373,    206,   9000,     29]], device='cuda:0') [477, 2828, 46786, 232, 7602, 7, 463, 3663, 17, 6213, 1827, 4996, 6603, 19, 12134, 44, 76, 76206, 732, 163, 5373, 206, 9000, 29]
tensor([[    11,   5866,   1245,     14,     47,  23718,      2,  57274,
             17,   2011,      2,   3141,    160,    101,     50,     29,
             11,    722,     14,     21,     76,   8878,     52,   3979,
             29]], device='cuda:0') [11, 5866, 1245, 14, 47, 23718, 2, 57274, 17, 2011, 2, 3141, 160, 101, 50, 29, 11, 722, 14, 21, 76, 8878, 52, 3979, 29]
tensor([[   232,   3668,  31210,     44,    783,    498,     73,     70,
           6220,     76,    129,     55,   2178,  12190,  25253,     19,
          39352,     33,    181,    602,     19,     11,  31596,     29]], device='cuda:0') [232, 3668, 31210, 4

tensor([[   783,    233,    337,     11,   6995,  14623,   1104,     55,
          30184,   2191,      2,     17,     11,  12143,     19,    339,
          59092,     52,   1293,     65,     55,  25069,     29,  32642,
           1656,     29]], device='cuda:0') [783, 233, 337, 11, 6995, 14623, 1104, 55, 30184, 2191, 2, 17, 11, 12143, 19, 339, 59092, 52, 1293, 65, 55, 25069, 29, 32642, 1656, 29]
tensor([[     6,    945,   6198,  41539,    101,     11,  22675,     19,
           4026,      2,  59649,  17280,     29,  62709,     17,  56055,
            233,   4146,    236,   2072,   1776,     11,   1040,     29]], device='cuda:0') [6, 945, 6198, 41539, 101, 11, 22675, 19, 4026, 2, 59649, 17280, 29, 62709, 17, 56055, 233, 4146, 236, 2072, 1776, 11, 1040, 29]
tensor([[    76,    129,     19,     11,   2072,     19,     55,   5432,
           7311,  13325,  16255,    103,   4676,   4430,      2,   2041,
           1801,      2,   3254,      2,    448,     44,   6600,  35774,
          25253

tensor([[  1877,     11,    495,     52,     95,    142,  29514,    144,
           1007,      2,     11,   5866,     52,   9859,    843,   5207,
              2,  26183,     17,   1476,     19,  53157,  14259,  32956,
             29]], device='cuda:0') [1877, 11, 495, 52, 95, 142, 29514, 144, 1007, 2, 11, 5866, 52, 9859, 843, 5207, 2, 26183, 17, 1476, 19, 53157, 14259, 32956, 29]
tensor([[   198,      2,   4580,     17,   3046,      2,     11,   5866,
           9676,   1267,  10977,     17,  14172,   8922,     14,    317,
             86,  17237,  20175,     19,   3298,    823,     17,   4596,
             29]], device='cuda:0') [198, 2, 4580, 17, 3046, 2, 11, 5866, 9676, 1267, 10977, 17, 14172, 8922, 14, 317, 86, 17237, 20175, 19, 3298, 823, 17, 4596, 29]
tensor([[ 1.3300e+02,  5.2000e+01,  5.5000e+01,  6.2490e+03,  1.7000e+01,
          1.5221e+04,  1.7990e+03,  4.4000e+01,  3.1820e+03,  3.4540e+03,
          8.1900e+02,  1.4000e+01,  2.3500e+02,  2.0000e+00,  1.7000e+01,
        

tensor([[ 30341,    129,  11506,     14,   2080,    129,  11371,   2170,
           2191,   4264,   2142,  12134,     39,   1824,  21447,     17,
          28032,   3709,  50852,      2,      3,   2514,      2,  82858,
             29,     93]], device='cuda:0') [30341, 129, 11506, 14, 2080, 129, 11371, 2170, 2191, 4264, 2142, 12134, 39, 1824, 21447, 17, 28032, 3709, 50852, 2, 3, 2514, 2, 82858, 29, 93]
tensor([[   422,     76,     52,   1515,     14,    337,     55,   2577,
           5866,  50565,     55,   9302,   1324,    110,     55,   7432,
             17,   4775,   2553,      2,  78338,  52481,   1281,   5783,
           1106,  10835,     29]], device='cuda:0') [422, 76, 52, 1515, 14, 337, 55, 2577, 5866, 50565, 55, 9302, 1324, 110, 55, 7432, 17, 4775, 2553, 2, 78338, 52481, 1281, 5783, 1106, 10835, 29]
tensor([[ 21292,    304,     65,    491,     55,   7330,     19,  45049,
            129,      5,     93,     29,     29,     29,    408,     11,
          17280,     93,   4127

tensor([[    11,  16255,     52,    984,  79087,    843,     76,    129,
          50118,     17,   6959,      2,   1820,      2,     17,    110,
          23466,      2,     76,     52,     70,    160,     44,  29704,
             29]], device='cuda:0') [11, 16255, 52, 984, 79087, 843, 76, 129, 50118, 17, 6959, 2, 1820, 2, 17, 110, 23466, 2, 76, 52, 70, 160, 44, 29704, 29]
tensor([[  3753,     11,    575,     19,  16255,     77,    375,   5859,
             29,  29680,    448,  77121,    104,   1787,     14,     47,
            957,    133,     52,     76,     29]], device='cuda:0') [3753, 11, 575, 19, 16255, 77, 375, 5859, 29, 29680, 448, 77121, 104, 1787, 14, 47, 957, 133, 52, 76, 29]
tensor([[    11,   5866,     52,     55,  61326,      2,    181,   5947,
            181,     11,  16692,   3534,   3547,  22330,   1991,    110,
             55,  44659,  14607,      2,    163,     76,    129,    206,
          31210,    392,     29]], device='cuda:0') [11, 5866, 52, 55, 61326, 2, 181

tensor([[ 1.2900e+02,  1.2853e+04,  1.3250e+03,  1.6550e+04,  3.7760e+03,
          1.2414e+05,  9.0000e+00,  1.1000e+01,  1.6665e+04,  2.0000e+00,
          1.7000e+01,  7.7000e+01,  1.9960e+03,  4.0080e+03,  1.4068e+04,
          2.1910e+03,  7.0000e+00,  1.1000e+01,  1.0099e+04,  1.8780e+03,
          1.7990e+03,  1.4000e+01,  5.5000e+01,  2.1138e+04,  3.4051e+04,
          2.9000e+01]], device='cuda:0') [129, 12853, 1325, 16550, 3776, 124136, 9, 11, 16665, 2, 17, 77, 1996, 4008, 14068, 2191, 7, 11, 10099, 1878, 1799, 14, 55, 21138, 34051, 29]
tensor([[ 3.0510e+03,  5.5000e+01,  1.2240e+03,  4.0260e+03,  5.9630e+04,
          1.6300e+02,  2.5000e+01,  9.6000e+01,  4.4000e+01,  4.3563e+04,
          1.1000e+01,  2.3718e+04,  1.4103e+04,  4.4800e+02,  5.6010e+03,
          7.6000e+01,  4.4640e+03,  2.0000e+00,  1.1000e+02,  8.0400e+02,
          3.2500e+02,  1.1000e+01,  8.3680e+03,  1.2578e+05,  8.2400e+02,
          5.6880e+03,  9.8810e+03,  2.9000e+01]], device='cuda:0') [3051, 55,

tensor([[ 86401,     52,    181,  38522,    448,   9506,     29,    163,
            110,    170,      2,  74357,   1252,      2,     76,    233,
             47,    984,    181,  14305,     17,  15221,   7115,     70,
          21528,     29]], device='cuda:0') [86401, 52, 181, 38522, 448, 9506, 29, 163, 110, 170, 2, 74357, 1252, 2, 76, 233, 47, 984, 181, 14305, 17, 15221, 7115, 70, 21528, 29]
tensor([[ 95189,      2,  12444,     17,  24437,  23718,      2,    133,
           3593,  24545,   5554,      9,    232,     25,   1056,   1740,
             44,     76,     73,    552,   6397,      2,     76,   3883,
           2423,     29]], device='cuda:0') [95189, 2, 12444, 17, 24437, 23718, 2, 133, 3593, 24545, 5554, 9, 232, 25, 1056, 1740, 44, 76, 73, 552, 6397, 2, 76, 3883, 2423, 29]
tensor([[    54,     23,    406,    931,  79688,   2183,   5802,    229,
            515,     11,   1929,  68032,     29,      3,    355,     11,
           2003,     52,    110,     11,  52280,    843,    

tensor([[  3796,  18296,  65753,     17,  19347,    110,     55,   3594,
             44,      3,  20041,     73,   1663,    603,     47,     55,
            301,  71511,   1693,     29,     29,     29,     55,  56852,
          55227,     19,  34284,  40258,     29]], device='cuda:0') [3796, 18296, 65753, 17, 19347, 110, 55, 3594, 44, 3, 20041, 73, 1663, 603, 47, 55, 301, 71511, 1693, 29, 29, 29, 55, 56852, 55227, 19, 34284, 40258, 29]
tensor([[    23,  14621,     55,    197,   1883,    949,    103,    195,
            129,    341,    392,     19,     11,     18,    129,    840,
            784,   9802,     17,    528,     76,  26568,      2,  31278,
              2,     17,  15488,     29]], device='cuda:0') [23, 14621, 55, 197, 1883, 949, 103, 195, 129, 341, 392, 19, 11, 18, 129, 840, 784, 9802, 17, 528, 76, 26568, 2, 31278, 2, 17, 15488, 29]
tensor([[    76,    129,    406,   5497,   1105,     17,  16891,  61230,
          38462,    117,      3,    444,  25138,    210,      9,     

tensor([[ 6.5000e+01,  1.7000e+02,  1.4510e+04,  1.9000e+01,  2.0600e+02,
          1.8963e+04,  8.7050e+03,  1.1000e+02,  4.5325e+04,  2.0000e+00,
          1.2900e+02,  1.5414e+04,  1.6550e+04,  1.0118e+04,  5.5000e+01,
          1.9930e+03,  5.8300e+03,  1.9000e+01,  5.9000e+02,  1.7000e+01,
          9.6439e+04,  1.4000e+01,  1.3800e+02,  1.1000e+01,  1.2280e+05,
          2.5473e+04,  1.2023e+04]], device='cuda:0') [65, 170, 14510, 19, 206, 18963, 8705, 110, 45325, 2, 129, 15414, 16550, 10118, 55, 1993, 5830, 19, 590, 17, 96439, 14, 138, 11, 122799, 25473, 12023]
tensor([[    11,   5866,     23,    206,   4710,   5618,     17,     77,
          18771,    786,    184,     11,   5866,    129,   5204,     44,
            160,   1569,  31812,      9,     44,   1291,      2,     44,
            917,     17,     44,   6934,     29]], device='cuda:0') [11, 5866, 23, 206, 4710, 5618, 17, 77, 18771, 786, 184, 11, 5866, 129, 5204, 44, 160, 1569, 31812, 9, 44, 1291, 2, 44, 917, 17, 44, 6934,

tensor([[ 3.8163e+04,  2.0000e+00,  5.9470e+03,  2.0000e+00,  7.2891e+04,
          1.7000e+01,  2.8210e+04,  3.4194e+04,  2.9000e+01,  2.9000e+01,
          2.9000e+01,  7.6000e+01,  1.2810e+03,  1.7682e+04,  5.5000e+01,
          3.8650e+03,  1.2023e+04,  1.7000e+01,  3.0630e+03,  1.1071e+04,
          2.0000e+00,  2.8618e+04,  2.9900e+02,  5.5000e+01,  1.1565e+04,
          2.0000e+00,  1.4779e+05,  2.1138e+04,  3.4051e+04,  2.9000e+01]], device='cuda:0') [38163, 2, 5947, 2, 72891, 17, 28210, 34194, 29, 29, 29, 76, 1281, 17682, 55, 3865, 12023, 17, 3063, 11071, 2, 28618, 299, 55, 11565, 2, 147790, 21138, 34051, 29]
tensor([[   517,   3154,     11,   1665,    408,     11,   1064,     17,
             11,   2008,   8843,   1078,    210,     19,   2250,   7115,
             44,     52,     14,    345,      2,     30,  66259,   2924,
              9,     11,  16665,     29]], device='cuda:0') [517, 3154, 11, 1665, 408, 11, 1064, 17, 11, 2008, 8843, 1078, 210, 19, 2250, 7115, 44, 52, 14,

tensor([[   142,   2923,    229,   6783,    160,     11,  19500,    110,
            129,   1569,     17,     96,    917,   2169,   7854,    594,
            123,     19,   3266,  13221,    299,   4791,    191,    164,
            528,    133,     55,  19530,  16255,     29]], device='cuda:0') [142, 2923, 229, 6783, 160, 11, 19500, 110, 129, 1569, 17, 96, 917, 2169, 7854, 594, 123, 19, 3266, 13221, 299, 4791, 191, 164, 528, 133, 55, 19530, 16255, 29]
tensor([[    11,    191,    164,    406,   6678,      7,     55,  27946,
              2,   7806,  28173,    131,     76,   3121,    110,   4365,
             19,     11,  34976,     29,     73,     14,   3156,     55,
          27946,      2,   7806,  34976,  29288,     29]], device='cuda:0') [11, 191, 164, 406, 6678, 7, 55, 27946, 2, 7806, 28173, 131, 76, 3121, 110, 4365, 19, 11, 34976, 29, 73, 14, 3156, 55, 27946, 2, 7806, 34976, 29288, 29]
tensor([[ 1.1000e+01,  9.7400e+02,  9.4340e+03,  2.2030e+03,  3.6630e+03,
          1.5900e+02,  

tensor([[ 21129,     14,    345,     44,   1580,   2422,    133,  16255,
            110,    556,      2,    783,  34075,     47,     96,  13223,
             65,     11,  46206,   5528,     19,  18133,     93,   4731,
            144,   1473,  11259,     52,     29]], device='cuda:0') [21129, 14, 345, 44, 1580, 2422, 133, 16255, 110, 556, 2, 783, 34075, 47, 96, 13223, 65, 11, 46206, 5528, 19, 18133, 93, 4731, 144, 1473, 11259, 52, 29]
tensor([[    11,   4040,     19,   2969,    322,   9777,     52,     39,
           2422,     55,   1540,     19,   7317,   3159,  75284,  55997,
            618,     14,    556,     55,  30328,     29,     77,  18771,
           2910,    110,    184,     11,   2400,  89629,     29]], device='cuda:0') [11, 4040, 19, 2969, 322, 9777, 52, 39, 2422, 55, 1540, 19, 7317, 3159, 75284, 55997, 618, 14, 556, 55, 30328, 29, 77, 18771, 2910, 110, 184, 11, 2400, 89629, 29]
tensor([[  5630,    181,     55,   3866,     19,    515,     76,   4545,
             39,     

tensor([[ 5.4000e+01,  1.5900e+02,  9.6000e+01,  1.2167e+04,  1.9000e+01,
          5.2300e+02,  3.7711e+04,  0.0000e+00,  1.1000e+01,  3.4976e+04,
          1.4400e+02,  9.8590e+03,  1.9568e+04,  3.0583e+04,  2.1000e+01,
          4.1781e+04,  1.1000e+01,  3.3500e+02,  8.7000e+01,  1.9000e+01,
          1.1000e+01,  5.8660e+03,  2.9000e+01,  7.6000e+01,  1.2900e+02,
          4.6000e+02,  5.5000e+01,  1.3020e+03,  1.0627e+05,  1.4400e+02,
          1.6255e+04,  2.9000e+01]], device='cuda:0') [54, 159, 96, 12167, 19, 523, 37711, 0, 11, 34976, 144, 9859, 19568, 30583, 21, 41781, 11, 335, 87, 19, 11, 5866, 29, 76, 129, 460, 55, 1302, 106268, 144, 16255, 29]
tensor([[ 1.7655e+04,  1.2900e+02,  4.9000e+01,  1.7000e+01,  1.4730e+03,
          5.2000e+01,  2.0600e+02,  6.1200e+02,  9.5270e+03,  2.0000e+00,
          1.6300e+02,  4.0250e+03,  2.0670e+04,  2.3000e+01,  9.3100e+02,
          9.6000e+01,  1.4000e+01,  1.9180e+03,  1.4400e+02,  4.6080e+03,
          1.1181e+05,  2.9000e+01,  2.58

tensor([[    99,    817,    716,      2,  11879,   3621,  25835,     17,
          13830,    151,  76206,  16613,     11,  14708,  13509,     93,
          13510,    110,    526,   1424,   3800,    843,     54,    129,
            984,    254,   1798,      2,  21005,     29]], device='cuda:0') [99, 817, 716, 2, 11879, 3621, 25835, 17, 13830, 151, 76206, 16613, 11, 14708, 13509, 93, 13510, 110, 526, 1424, 3800, 843, 54, 129, 984, 254, 1798, 2, 21005, 29]
tensor([[    11,   1881,   6213,     11,  80738,   7608,     17,   2712,
           3385,    647,    163,     65,  12367,      2,     17,     55,
           9815,   6035,    649,      2,     65,    206,  56376,  85062,
             19,  62749,  31883,   4654,    110,      0,     49,   3236,
             29]], device='cuda:0') [11, 1881, 6213, 11, 80738, 7608, 17, 2712, 3385, 647, 163, 65, 12367, 2, 17, 55, 9815, 6035, 649, 2, 65, 206, 56376, 85062, 19, 62749, 31883, 4654, 110, 0, 49, 3236, 29]
tensor([[   101,    170,    974,      2,   

tensor([[ 6.2749e+04,  1.0092e+05,  6.0000e+00,  6.2200e+03,  2.2430e+03,
          9.0010e+03,  1.4820e+03,  1.3300e+02,  1.7980e+03,  1.7000e+01,
          1.1000e+01,  2.4880e+04,  1.6400e+04,  1.7000e+01,  7.1082e+04,
          2.0000e+00,  2.1000e+01,  2.5900e+02,  2.4200e+02,  6.5000e+01,
          2.6260e+03,  5.2300e+02,  5.5948e+04,  1.1000e+01,  1.6610e+03,
          1.9000e+01,  2.4360e+04,  1.8660e+03,  1.5658e+04,  2.9000e+01]], device='cuda:0') [62749, 100925, 6, 6220, 2243, 9001, 1482, 133, 1798, 17, 11, 24880, 16400, 17, 71082, 2, 21, 259, 242, 65, 2626, 523, 55948, 11, 1661, 19, 24360, 1866, 15658, 29]
tensor([[   432,     17,  17668,     11,     96,  69254,    888,     19,
           1705,     93,     17,     11,    888,     19,   1705,      2,
             93,     70,    181,     76,   1172,    210,    532,   1736,
             11,    389,    159,     29]], device='cuda:0') [432, 17, 17668, 11, 96, 69254, 888, 19, 1705, 93, 17, 11, 888, 19, 1705, 2, 93, 70, 181, 76, 

tensor([[  3582,    181,     76,     46,   1737,      2,    133,   5866,
            129,   1720,     52,     70,     96,  15605,    144,  24677,
              2,    200,    552,    325,     76,   5777,  12556,   6799,
             17,   5124,   9480,    181,    804,     19,     11,    591,
           5481,     29]], device='cuda:0') [3582, 181, 76, 46, 1737, 2, 133, 5866, 129, 1720, 52, 70, 96, 15605, 144, 24677, 2, 200, 552, 325, 76, 5777, 12556, 6799, 17, 5124, 9480, 181, 804, 19, 11, 591, 5481, 29]
tensor([[ 1.1000e+01,  5.8660e+03,  1.2900e+02,  1.0953e+05,  4.4470e+03,
          5.2000e+01,  9.7300e+02,  3.9200e+02,  1.9000e+01,  1.7000e+02,
          2.8130e+03,  2.9000e+01,  3.4810e+03,  8.3490e+03,  2.0000e+00,
          1.1000e+01,  1.7990e+03,  4.8790e+04,  3.9000e+01,  5.5000e+01,
          1.6292e+04,  5.8960e+03,  4.0470e+03,  1.7000e+01,  3.6000e+03,
          6.5000e+01,  1.1000e+01,  2.7528e+04,  4.6810e+03,  1.9000e+01,
          5.5000e+01,  5.9580e+03,  2.3273e+04, 

tensor([[   840,  57893,   2706,  21680,    210,    985,    229,   2269,
          25910,  25358,    448,  10748,  16993,   1273,  86401,   3045,
            629,     65,     11,  19895,   2003,     44,     11,    512,
           4625,     46,     47,   7133,      0,    629,    101,   3709,
             29]], device='cuda:0') [840, 57893, 2706, 21680, 210, 985, 229, 2269, 25910, 25358, 448, 10748, 16993, 1273, 86401, 3045, 629, 65, 11, 19895, 2003, 44, 11, 512, 4625, 46, 47, 7133, 0, 629, 101, 3709, 29]
tensor([[ 1.1000e+01,  1.1400e+05,  1.8580e+03,  1.4000e+01,  1.6400e+02,
          3.0890e+03,  7.5240e+03,  1.3300e+02,  7.7370e+03,  1.7980e+03,
          2.0000e+00,  1.6300e+02,  7.0000e+01,  9.6000e+01,  4.7670e+03,
          5.2000e+01,  5.3200e+02,  1.7000e+02,  1.0425e+04,  9.7300e+02,
          5.3900e+03,  1.4000e+01,  1.4800e+03,  5.1500e+02,  5.2800e+02,
          2.9534e+04,  1.2900e+02,  2.4237e+04,  2.3200e+02,  5.3930e+03,
          1.7000e+01,  1.1882e+04,  2.9000e+01]

tensor([[ 15737,  21345,     52,    110,   1473,   4402,    405,      2,
             50,    959,    621,     14,  13492,    236,    512,   8490,
             17,     70,   4791,    299,     55,   6383,     44,      2,
            110,     25,    463,   1474,    191,     47,   3796,  64947,
             29]], device='cuda:0') [15737, 21345, 52, 110, 1473, 4402, 405, 2, 50, 959, 621, 14, 13492, 236, 512, 8490, 17, 70, 4791, 299, 55, 6383, 44, 2, 110, 25, 463, 1474, 191, 47, 3796, 64947, 29]
tensor([[  2712,   2885,   3643,    517,   8303,     86,   4079,     78,
           1596,     39,     11,   4079,     14,   2885,    376,    110,
             29,     29,     29,    322,   4026,  13326,   2082,  11199,
           1687,      7,     11,   1720,     29,     29,     29]], device='cuda:0') [2712, 2885, 3643, 517, 8303, 86, 4079, 78, 1596, 39, 11, 4079, 14, 2885, 376, 110, 29, 29, 29, 322, 4026, 13326, 2082, 11199, 1687, 7, 11, 1720, 29, 29, 29]
tensor([[   133,  11035,   2032,      9,    

tensor([[ 19848,    281,    164,     55,  16213,    917,    101,    133,
          24751,   2910,  16255,     29,     17,   2136,      6,    101,
            118,    164,     55,   1415,   2761,     19,     11,   4002,
             14,   4062,     11,   5866,    129,  12366,    159,    110,
             11,  28362,     29]], device='cuda:0') [19848, 281, 164, 55, 16213, 917, 101, 133, 24751, 2910, 16255, 29, 17, 2136, 6, 101, 118, 164, 55, 1415, 2761, 19, 11, 4002, 14, 4062, 11, 5866, 129, 12366, 159, 110, 11, 28362, 29]
tensor([[   172,     19,    339,   9802,     23,     11,    687,      0,
            786,    184,    206,  19251,  10231,     17,      2,    163,
           4438,   7347,    229,    392,   1894,      2,      0,    160,
            170,   9501,     17,   9135,      2,   1281,  20600,     14,
            105,  62934,  10766,     29]], device='cuda:0') [172, 19, 339, 9802, 23, 11, 687, 0, 786, 184, 206, 19251, 10231, 17, 2, 163, 4438, 7347, 229, 392, 1894, 2, 0, 160, 170,

tensor([[    39,  42988,    445,   8525,    794,   1172,      0,  61061,
             29,     76,    445,    362,    184,    809,     55,  62934,
           8271,     65,     55,   6272,   4725,      2,     17,    184,
           5465,    170,    688,   9000,     19,   5714,  19848,    236,
           1515,    928,   3476,     17,   9135,     29]], device='cuda:0') [39, 42988, 445, 8525, 794, 1172, 0, 61061, 29, 76, 445, 362, 184, 809, 55, 62934, 8271, 65, 55, 6272, 4725, 2, 17, 184, 5465, 170, 688, 9000, 19, 5714, 19848, 236, 1515, 928, 3476, 17, 9135, 29]
tensor([[    54,    159,    181,     25,  30398,    181,  22454,      2,
            163,   1805,      2,     76,  17682,  31335,    110,     11,
          72475,     19,    591,   6799,      2,     17,     76,    129,
             55,   1515,   4965,     14,     11,  10440,     19,     55,
          69781,     44,    281,   3589,      9,  14623,     29]], device='cuda:0') [54, 159, 181, 25, 30398, 181, 22454, 2, 163, 1805, 2, 76, 1

tensor([[ 3.9970e+03,  1.1000e+01,  4.7400e+02,  4.3250e+03,  1.2134e+04,
          3.3000e+01,  1.8100e+02,  3.0353e+04,  1.8737e+04,  1.7000e+01,
          1.8390e+03,  2.4690e+04,  5.5000e+01,  9.1884e+04,  2.6188e+04,
          1.4000e+01,  8.6000e+01,  4.6902e+04,  4.5100e+02,  0.0000e+00,
          1.4650e+03,  2.0000e+00,  5.0000e+00,  5.2000e+01,  5.8515e+04,
          9.5700e+02,  5.2000e+01,  2.0600e+02,  7.4128e+04,  1.7000e+01,
          1.0295e+05,  1.4594e+05,  3.7600e+02,  0.0000e+00,  4.4000e+01,
          1.8920e+03,  2.4003e+04,  2.9000e+01]], device='cuda:0') [3997, 11, 474, 4325, 12134, 33, 181, 30353, 18737, 17, 1839, 24690, 55, 91884, 26188, 14, 86, 46902, 451, 0, 1465, 2, 5, 52, 58515, 957, 52, 206, 74128, 17, 102954, 145938, 376, 0, 44, 1892, 24003, 29]
tensor([[ 1.1000e+01,  1.7980e+03,  1.9000e+01,  7.2350e+03,  9.9800e+02,
          1.0840e+03,  2.9000e+01,  2.9000e+01,  2.9000e+01,  5.2000e+01,
          2.3200e+02,  2.8332e+04,  7.6000e+01,  2.6010e+03,  1.

tensor([[   110,    463,   1167,      2,     76,    129,    984,    187,
           1123,   2492,     29,   2365,    133,    392,    460,    517,
              0,    110,   1720,    515,     76,   3063,    110,   9579,
          19159,     29,   2874,      2,     39,      3,   1400,    763,
             29,     29,     29,     76,    129,  10476,   2789,   2789]], device='cuda:0') [110, 463, 1167, 2, 76, 129, 984, 187, 1123, 2492, 29, 2365, 133, 392, 460, 517, 0, 110, 1720, 515, 76, 3063, 110, 9579, 19159, 29, 2874, 2, 39, 3, 1400, 763, 29, 29, 29, 76, 129, 10476, 2789, 2789]
tensor([[   200,    783,  18771,    702,    210,      9,     76,    129,
             55,   8100,   1569,  11425,     17,  41066,     65,     55,
           8975,  66259,      2,     76,    498,    984,     47,     11,
          16255,    783,  18771,    376,      0,     29,     76,   7030,
              9,    532,    108,  66255,    450,    299,    257,   7191,
           6383,     29]], device='cuda:0') [200, 78

2018-05-25 15:07:24,512 : Generated sentence embeddings
2018-05-25 15:07:24,513 : Training sklearn-LogReg with (inner) 10-fold cross-validation


tensor([[ 1.8100e+02,  2.0600e+02,  1.4750e+03,  1.2900e+02,  2.0197e+04,
          2.0000e+00,  3.0825e+04,  1.2900e+02,  1.7790e+03,  2.3000e+01,
          9.3100e+02,  1.4000e+01,  4.1680e+03,  7.6000e+01,  2.0000e+00,
          7.0000e+01,  2.0000e+02,  1.1000e+01,  1.2123e+05,  5.2000e+01,
          7.3000e+01,  1.1000e+01,  8.4000e+02,  3.9790e+03,  1.5260e+03,
          2.9000e+01,  1.8100e+02,  5.5000e+01,  1.7980e+03,  1.9000e+01,
          1.1060e+03,  7.6950e+03,  2.0000e+00,  1.1000e+01,  2.9535e+04,
          1.8400e+02,  2.9378e+04,  1.7000e+01,  2.7056e+04,  3.6750e+03,
          3.0450e+03,  5.2100e+02,  1.4000e+01,  4.7000e+01,  5.7000e+03,
          2.9000e+01]], device='cuda:0') [181, 206, 1475, 129, 20197, 2, 30825, 129, 1779, 23, 931, 14, 4168, 76, 2, 70, 200, 11, 121228, 52, 73, 11, 840, 3979, 1526, 29, 181, 55, 1798, 19, 1106, 7695, 2, 11, 29535, 184, 29378, 17, 27056, 3675, 3045, 521, 14, 47, 5700, 29]
tensor([[    54,     52,    521,    110,   1476,  32028,    

2018-05-25 15:07:29,457 : Best param found at split 1: l2reg = 0.25                 with score 63.77


KeyboardInterrupt: 

In [25]:
EA_res = {'TREC': {'acc': 57.4, 'ndev': 5452, 'devacc': 53.56, 'ntest': 500}, 'SST2': {'acc': 67.11, 'ndev': 872, 'devacc': 67.2, 'ntest': 1821}, 'CR': {'acc': 70.65, 'ndev': 3775, 'devacc': 70.64, 'ntest': 3775}, 'MPQA': {'acc': 83.78, 'ndev': 10606, 'devacc': 83.89, 'ntest': 10606}, 'MR': {'acc': 64.72, 'ndev': 10662, 'devacc': 64.53, 'ntest': 10662}, 'STS14': {'headlines': {'pearson': (0.5781994919225272, 4.020000246168714e-68), 'nsamples': 750, 'spearman': 'SpearmanrResult(correlation=0.5705232857978165, pvalue=5.589791453157285e-66)'}, 'deft-news': {'pearson': (0.6220449533709097, 1.6081763124275315e-33), 'nsamples': 300, 'spearman': 'SpearmanrResult(correlation=0.578333454614915, pvalue=3.56018796171822e-28)'}, 'images': {'pearson': (0.6578237117176955, 3.654157740608177e-94), 'nsamples': 750, 'spearman': 'SpearmanrResult(correlation=0.6438621123340441, pvalue=4.9441358581162626e-89)'}, 'OnWN': {'pearson': (0.658846051664604, 1.5004930667755487e-94), 'nsamples': 750, 'spearman': 'SpearmanrResult(correlation=0.7165302641879749, pvalue=4.038459846586195e-119)'}, 'tweet-news': {'pearson': (0.6233064013917692, 6.006549841321549e-82), 'nsamples': 750, 'spearman': 'SpearmanrResult(correlation=0.552714320253843, pvalue=3.22156860724007e-61)'}, 'all': {'pearson': {'mean': 0.5813380714320986, 'wmean': 0.5951356658320022}, 'spearman': {'mean': 0.5708291603366306, 'wmean': 0.5865540558636717}}, 'deft-forum': {'pearson': (0.3478078185250862, 3.053271390924939e-14), 'nsamples': 450, 'spearman': 'SpearmanrResult(correlation=0.3630115248311902, pvalue=1.833847351421204e-15)'}}, 'SICKEntailment': {'acc': 74.75, 'ndev': 500, 'devacc': 72.6, 'ntest': 4927}, 'MRPC': {'acc': 70.96, 'f1': 80.1, 'devacc': 70.61, 'ndev': 4076, 'ntest': 1725}, 'SUBJ': {'acc': 79.15, 'ndev': 10000, 'devacc': 79.17, 'ntest': 10000}}
SG_avg_res = {'SUBJ': {'acc': 79.83, 'devacc': 79.93, 'ntest': 10000, 'ndev': 10000}, 'MR': {'acc': 64.91, 'devacc': 65.06, 'ntest': 10662, 'ndev': 10662}, 'CR': {'acc': 70.6, 'devacc': 70.57, 'ntest': 3775, 'ndev': 3775}, 'STS14': {'deft-forum': {'spearman': 'SpearmanrResult(correlation=0.30898757056284787, pvalue=2.0691854690433753e-11)', 'pearson': (0.27256288243965693, 4.1651890020195675e-09), 'nsamples': 450}, 'images': {'spearman': 'SpearmanrResult(correlation=0.4408194211200905, pvalue=5.280384646229476e-37)', 'pearson': (0.4117261507554508, 4.7518699650716877e-32), 'nsamples': 750}, 'deft-news': {'spearman': 'SpearmanrResult(correlation=0.5647511600041103, pvalue=1.13194354561933e-26)', 'pearson': (0.5422089540432408, 2.509906356244403e-24), 'nsamples': 300}, 'all': {'spearman': {'mean': 0.48469429259169844, 'wmean': 0.48914400626451704}, 'pearson': {'mean': 0.45847437877611935, 'wmean': 0.4632991494509817}}, 'OnWN': {'spearman': 'SpearmanrResult(correlation=0.5986940260146392, pvalue=3.933092783581038e-74)', 'pearson': (0.5214190523169768, 1.6237220055815684e-53), 'nsamples': 750}, 'tweet-news': {'spearman': 'SpearmanrResult(correlation=0.5375884592346126, pvalue=2.147350633544745e-57)', 'pearson': (0.5341431243615529, 1.4997705284872292e-56), 'nsamples': 750}, 'headlines': {'spearman': 'SpearmanrResult(correlation=0.4573251186138901, pvalue=4.902572881630306e-40)', 'pearson': (0.4687861087398376, 3.055636088817881e-42), 'nsamples': 750}}, 'SST2': {'acc': 64.31, 'devacc': 63.99, 'ntest': 1821, 'ndev': 872}, 'TREC': {'acc': 53.8, 'devacc': 53.52, 'ntest': 500, 'ndev': 5452}, 'SICKEntailment': {'acc': 67.73, 'devacc': 69.6, 'ntest': 4927, 'ndev': 500}, 'MPQA': {'acc': 83.59, 'devacc': 83.62, 'ntest': 10606, 'ndev': 10606}, 'MRPC': {'acc': 70.14, 'f1': 80.23, 'devacc': 70.56, 'ntest': 1725, 'ndev': 4076}}
SG_tfidf_res = {'SUBJ': {'acc': 77.51, 'devacc': 77.53, 'ntest': 10000, 'ndev': 10000}, 'MR': {'acc': 64.24, 'devacc': 64.07, 'ntest': 10662, 'ndev': 10662}, 'CR': {'acc': 69.22, 'devacc': 69.41, 'ntest': 3775, 'ndev': 3775}, 'STS14': {'deft-forum': {'spearman': 'SpearmanrResult(correlation=0.316315651904115, pvalue=6.4858192321523515e-12)', 'pearson': (0.276666708551114, 2.378646491257731e-09), 'nsamples': 450}, 'images': {'spearman': 'SpearmanrResult(correlation=0.45347644118861796, pvalue=2.5846122070851603e-39)', 'pearson': (0.4355811792783599, 4.473764339992488e-36), 'nsamples': 750}, 'deft-news': {'spearman': 'SpearmanrResult(correlation=0.5484910896581424, pvalue=5.803318096557867e-25)', 'pearson': (0.5601467570097868, 3.528331007610503e-26), 'nsamples': 300}, 'all': {'spearman': {'mean': 0.5085991098439903, 'wmean': 0.519194748901482}, 'pearson': {'mean': 0.49753726563574924, 'wmean': 0.5076937712376356}}, 'OnWN': {'spearman': 'SpearmanrResult(correlation=0.7023028905428166, pvalue=1.6489620448032347e-112)', 'pearson': (0.6749156474824787, 7.848620112501906e-101), 'nsamples': 750}, 'tweet-news': {'spearman': 'SpearmanrResult(correlation=0.5582633328557121, pvalue=1.1364337930928656e-62)', 'pearson': (0.5582010433457185, 1.1803246262212194e-62), 'nsamples': 750}, 'headlines': {'spearman': 'SpearmanrResult(correlation=0.4727452529145376, pvalue=5.053919999036877e-43)', 'pearson': (0.4797122581470376, 2.010716425101528e-44), 'nsamples': 750}}, 'SST2': {'acc': 64.8, 'devacc': 64.22, 'ntest': 1821, 'ndev': 872}, 'TREC': {'acc': 48.8, 'devacc': 48.79, 'ntest': 500, 'ndev': 5452}, 'SICKEntailment': {'acc': 64.52, 'devacc': 63.8, 'ntest': 4927, 'ndev': 500}, 'MPQA': {'acc': 83.28, 'devacc': 83.47, 'ntest': 10606, 'ndev': 10606}, 'MRPC': {'acc': 69.68, 'f1': 80.08, 'devacc': 70.46, 'ntest': 1725, 'ndev': 4076}}

for res in [EA_res, SG_avg_res, SG_tfidf_res]:
    for key, value in res.items():
        if key == "STS14":
            print('{}: {}'.format(key, value['all']))
        else:
            print('{}: {}'.format(key, value))
        print('___________________________')
    print("\n-----------------------------------------\n")

SUBJ: {'acc': 79.15, 'devacc': 79.17, 'ntest': 10000, 'ndev': 10000}
___________________________
MR: {'acc': 64.72, 'devacc': 64.53, 'ntest': 10662, 'ndev': 10662}
___________________________
CR: {'acc': 70.65, 'devacc': 70.64, 'ntest': 3775, 'ndev': 3775}
___________________________
STS14: {'spearman': {'mean': 0.5708291603366306, 'wmean': 0.5865540558636717}, 'pearson': {'mean': 0.5813380714320986, 'wmean': 0.5951356658320022}}
___________________________
SST2: {'acc': 67.11, 'devacc': 67.2, 'ntest': 1821, 'ndev': 872}
___________________________
TREC: {'acc': 57.4, 'devacc': 53.56, 'ntest': 500, 'ndev': 5452}
___________________________
SICKEntailment: {'acc': 74.75, 'devacc': 72.6, 'ntest': 4927, 'ndev': 500}
___________________________
MPQA: {'acc': 83.78, 'devacc': 83.89, 'ntest': 10606, 'ndev': 10606}
___________________________
MRPC: {'acc': 70.96, 'f1': 80.1, 'devacc': 70.61, 'ntest': 1725, 'ndev': 4076}
___________________________

-----------------------------------------

S